enemy_color: "red"
# enemy_color: "blue"

#####-----神经网络参数-----#####
classify_model: assets/tiny_resnet.onnx
yolov5_engine_path: assets/0526.engine
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
# min_confidence: 0.8

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: -0.5 # degree -RIGHT +LEFT
pitch_offset: 1.3 # degree +up -down
comming_angle: 55 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.020 # s
low_speed_delay_time: 0.018 # s planner use this value

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 2.5
gain: 16.9
vid_pid: "2bdf:0001"

#####-----calibration-----#####
# 重投影误差: 0.1044px
camera_matrix: [2431.5442906536896, 0, 731.11693266521172, 0, 2431.981935518676, 571.97253687188845, 0, 0, 1]
distort_coeffs: [-0.024537214279889235, 0.18178821826451871, 0.0011995536783585903, 0.0007629857361170718, 0]

#####-----handeye_calibration-----#####
# 手动填写 R_gimbal2imubody
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 相机同理想情况的偏角: yaw-0.22 pitch-0.56 roll1.57 degree
R_camera2gimbal: [0.0035655563819170233, -0.0097933594363243184, 0.99994568698436737, -0.99962051713606803, 0.027278944966046437, 0.0038315639312575421, -0.027314987247064149, -0.99957988638852191, -0.009692378407922364]
t_camera2gimbal: [0.054936022294336258, 0.016981319870998244, 0.088825792031006157]

#####-----gimbal参数-----#####
com_port: "/dev/ttyACM0"
protocol: "neo"
baud_rate: 921600

#####-----planner-----#####
fire_thresh: 0.0035

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
buff_engine_path: assets/yolo11_buff_int8.engine

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.120     # s
